# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# ======================================================================
# === about ============================================================
# ======================================================================
[[main]]
  name = "About us"
  url = "#about"
  weight = 10

[[main]]
  name = "Description"
  weight = 10
  parent = "About us"
  url = "about/description"

[[main]]
  name = "Mission"
  weight = 20
  parent = "About us"
  url = "about/mission"

[[main]]
  name = "Vision"
  weight = 30
  parent = "About us"
  url = "about/vision"

[[main]]
  name = "Guiding Principles"
  weight = 40
  parent = "About us"
  url = "about/guiding_principles"

[[main]]
  name = "Ethics and Value"
  weight = 50
  parent = "About us"
  url = "about/ethics_and_value"

[[main]]
  name = "Timeline"
  weight = 60
  parent = "About us"
  url = "about/timeline"

[[main]]
  name = "People"
  weight = 70
  parent = "About us"
  url = "about/people"

[[main]]
  name = "Strategy and Implementation"
  weight = 80
  parent = "About us"
  url = "about/strategy_and_implementation"
# ======================================================================
# === /about ===========================================================
# ======================================================================

[[main]]
  name = "The Network"
  url = "#posts"
  weight = 20

[[main]]
  name = "Join MBON"
  url = "#projects"
  weight = 30
  parent = "Posts"

[[main]]
  name = "Media"
  url = "#talks"
  weight = 40

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 50

[[main]]
  name = "Contacts"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
